const foodRecipesJS = [
  {
    Recipe: "Drunken Noodles",
    Cuisine: "Thai",
    Id: 1,
    Image: "/images/drunken-noodles-dish.jpg",
    IngredientsImage: ["/images/drunken-noodles-ingredients.jpg"],
    Ingredients: [
      "Rice noodles",
      "Thai basil",
      "Chicken thighs",
      "Thai chiles/seranos",
      "Green onion",
      "Ginger",
      "Garlic",
      "Fish sauce",
      "Sesame oil",
      "Soy sauce",
      "Oyster sauce",
    ],
    Description: "One of my favorite Thai dishes that truly slaps.",
    StepImages: [
      "/images/drunken-noodles-step-1.jpg",
      "/images/drunken-noodles-step-2.jpg",
      "/images/drunken-noodles-dish.jpg",
    ],
  },
  {
    Recipe: "Spaghetti and Meat Sauce",
    Cuisine: "Italian",
    Id: 2,
    Image: "/images/spaghetti_plate.jpg",
    IngredientsImage: ["/images/spaghetti_ingredients.jpg"],
    Ingredients: [
      "1 lb Italian Sausage",
      "Chicken stock",
      "2 cans crushed tomatoes",
      "Parmesan cheese",
      "White wine",
      "1-2 stocks celery",
      "1 yellow onion",
      "Olive oil",
      "4-5 garlic cloves",
      "Tomato paste",
      "Salt",
      "Pepper",
      "Italian Season",
      "Fresh parsley",
    ],
    Description:
      "A timeless dinner. I've gone through many recipe iterations to find my favorite version, I hope you enjoy.",
    StepImages: [
      "/images/spaghetti_prep_1.jpg",
      "/images/spaghetti_prep_1.1.jpg",
      "/images/spaghetti_prep_2.jpg",
      "/images/spaghetti_prep_3.jpg",
      "/images/spaghetti_prep_4.jpg",
      "/images/spaghetti_prep_5.jpg",
    ],
  },
  {
    Recipe: "Lasagna",
    Cuisine: "Italian",
    Id: 3,
    Image: "/images/lasagna-slice.jpg",
    IngredientsImage: ["/images/lasagna-ingredients.jpg"],
    Ingredients: [
      "Two cans Tomato sauce",
      "Ground beef",
      "Ground Italian sausage",
      "Yellow onion",
      "Garlic",
      "One egg",
      "Italian Parsley",
      "Ricotta Cheese",
      "Fresh Mozzarella",
      "Parmesan cheese",
      "Basil",
      "Lasagna noodles",
    ],
    Description: "Inject it into my veins.",
    StepImages: [
      "/images/lasagna-beef-pork-1.jpg",
      "/images/lasagna-cooking-1.jpg",
      "/images/lasagna-uncooked.jpg",
      "/images/lasagna-cooked.jpg",
    ],
  },
  {
    Recipe: "Shrimp Scampi",
    Cuisine: "Italian",
    Id: 4,
    Image: "/images/coNomNomsLogo.png",
    IngredientsImage: [""],
    Ingredients:
      "Rice noodles, thai basil, chicken thighs, Thai chiles/seranos, etc ",
    Description: "Overcooking shrimp is my middle name.",
    StepImages: [""],
  },
  {
    Recipe: "Chicken Gyro",
    Cuisine: "Mediterranean",
    Id: 5,
    Image: "/images/coNomNomsLogo.png",
    IngredientsImage: [""],
    Ingredients:
      "A lot of stuff. ",
    Description: "Recipe coming soon yo.",
    StepImages: [""],
  },
  {
    Recipe: "Jalapeno Salsa",
    Cuisine: "Mexican",
    Id: 6,
    Image: "/images/coNomNomsLogo.png",
    IngredientsImage: [""],
    Ingredients: ["Jalapenos, Onion, Garlic, Cilantro, Canola oil, Salt"],
    Description: "Recipe coming soon broooooo.",
    StepImages: [""],
  },
];

export default foodRecipesJS;
