const foodRecipesJS = [
  {
    Recipe: "Drunken Noodles",
    Cuisine: "Thai",
    Id: 1,
    Image: "/images/drunken-noodles-dish.jpg",
    IngredientsImage: ["/images/drunken-noodles-ingredients.jpg"],
    Ingredients: [
      "Rice noodles",
      "Thai basil",
      "Chicken thighs",
      "Thai chiles/seranos",
      "Green onion",
      "Ginger",
      "Garlic",
      "Fish sauce",
      "Sesame oil",
      "Soy sauce",
      "Oyster sauce",
    ],
    Description: "One of my favorite Thai dishes that truly slaps.",
    StepImages: [
      "/images/drunken-noodles-step-1.jpg",
      "/images/drunken-noodles-step-2.jpg",
      "/images/drunken-noodles-dish.jpg",
    ],
  },
  {
    Recipe: "Chicken Gyro",
    Cuisine: "Mediterranean",
    Id: 2,
    Image: "/images/coNomNomsLogo.png",
    IngredientsImage: [""],
    Ingredients:
      "Rice noodles, thai basil, chicken thighs, Thai chiles/seranos, etc ",
    Description: "An easy and delicious Mediterranean classic.",
    StepImages: [""],
  },
  {
    Recipe: "Lasagna",
    Cuisine: "Italian",
    Id: 3,
    Image: "/images/lasagna-slice.jpg",
    IngredientsImage: ["/images/lasagna-ingredients.jpg"],
    Ingredients: [
      "Two cans Tomato sauce",
      "Ground beef",
      "Ground Italian sausage",
      "Yellow onion",
      "Garlic",
      "One egg",
      "Italian Parsley",
      "Ricotta Cheese",
      "Fresh Mozzarella",
      "Parmesan cheese",
      "Basil",
      "Lasagna noodles",
    ],
    Description: "Inject it into my veins.",
    StepImages: [
      "/images/lasagna-beef-pork-1.jpg",
      "/images/lasagna-cooking-1.jpg",
      "/images/lasagna-uncooked.jpg",
      "/images/lasagna-cooked.jpg",
    ],
  },
  {
    Recipe: "Shrimp Scampi",
    Cuisine: "Italian",
    Id: 4,
    Image: "/images/coNomNomsLogo.png",
    IngredientsImage: [""],
    Ingredients:
      "Rice noodles, thai basil, chicken thighs, Thai chiles/seranos, etc ",
    Description: "Overcooking shrimp is my middle name.",
    StepImages: [""],
  },
];

export default foodRecipesJS;
